### ISSUE TITLE
BUG - Action fails with java.nio.file.NoSuchFileException when downloading the install.sh script

### ISSUE THREAD

**Issue by lmrb-1968** [xygeni/xygeni-action#4]
From customer Napptive (user: daniel@napptive.com):

> Estaba intentando integrar el primer repositorio con la herramienta mediante GitHub actions y nos da un error que parece venir de la acción en sí. Te adjunto el snippet del workflow que hemos creado, y el error que sale al ejecutar la acción.

> Snippet de la acción:

```yaml
xygeni-scan:
  name: Xygeni Scan
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Xygeni-Scanner
      uses: xygeni/xygeni-action@v1.2
      id: Xygeni-Scanner
      with:
        token: ${{ secrets.XYGENI_TOKEN }}
```

> Error de la acción:

```
usr/bin/docker run --name bee76095724e37a2a12bd9abb0ec9a_a70419 --label 290506 --workdir /github/workspace --rm -e "GOPRIVATE" -e "GH_NAPP_USER" -e "GH_NAPP_TOKEN" -e "INPUT_TOKEN" -e "INPUT_XYGENI_URL" -e "INPUT_PROJECT" -e "INPUT_DIRECTORY" -e "INPUT_USERNAME" -e "INPUT_PASSWORD" -e "INPUT_RUN" -e "INPUT_INCLUDE" -e "INPUT_EXCLUDE" -e "INPUT_OUTPUT" -e "INPUT_FORMAT" -e "INPUT_COLUMNS" -e "INPUT_CODE" -e "INPUT_CONF" -e "INPUT_BASELINE" -e "INPUT_CUSTOM_DETECTORS_DIR" -e "INPUT_DETECTORS" -e "INPUT_SKIP_DETECTORS" -e "INPUT_SBOM" -e "INPUT_SBOM_FORMAT" -e "INPUT_SECRETS_MODE" -e "INPUT_STANDARD" -e "INPUT_FAIL_ON" -e "INPUT_TRY_ALL_SCANS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/oauth/oauth":"/github/workspace" 290506:99bee76095724e37a2a12bd9abb0ec9a
[main] INFO io.xygeni.github.action.XygeniGitHubAction - Starting scanner action...
[main] ERROR io.xygeni.github.action.XygeniGitHubAction - Error executing xygeni-action: /home/runner/work/_temp/install.sh
java.nio.file.NoSuchFileException: /home/runner/work/_temp/install.sh
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
at java.base/java.nio.file.Files.copy(Files.java:3067)
at io.xygeni.github.action.XygeniGitHubAction.downloadScriptInstaller(XygeniGitHubAction.java:229)
at io.xygeni.github.action.XygeniGitHubAction.main(XygeniGitHubAction.java:133)
```

**Comment by lmrb-1968** [comment]
Tried to call endpoint GET /latest/scanner/install.sh with my production api token. and it returns `content-length: 0`:


```
curl -v -H "Authorization: Bearer ${XYGENI_TOKEN}" https://api.xygeni.io/latest/scanner/install.sh
```

Response is:
```
*   Trying 34.254.7.149:443...
* Connected to api.xygeni.io (34.254.7.149) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=xygeni.io
*  start date: Oct 25 00:00:00 2022 GMT
*  expire date: Nov 23 23:59:59 2023 GMT
*  subjectAltName: host "api.xygeni.io" matched cert's "*.xygeni.io"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x560651acde80)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /latest/scanner/install.sh HTTP/2
> Host: api.xygeni.io
> user-agent: curl/7.81.0
> accept: */*
> authorization: Bearer xya_eyJhbG__RESTO DE BYTES DEL TOKEN SIGUEN__R3ckYg
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 401
< date: Mon, 09 Jan 2023 18:11:39 GMT
< content-length: 0
< server: nginx
< vary: Origin
< vary: Access-Control-Request-Method
< vary: Access-Control-Request-Headers
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< pragma: no-cache
< expires: 0
< x-frame-options: DENY
<
* Connection #0 to host api.xygeni.io left intact
```

**Comment by Garcel** [comment]
As far as I remember the installation script download is not authenticated. However, credentials should be passed when running the script so it can authenticate the subsequent scanner download, which is authenticated.

**Comment by Garcel** [comment]
The command should be `curl -l https://get.xygeni.io/latest/scanner/install.sh`

**Comment by lmrb-1968** [comment]
Sure ! 

But unfortunately the `XygeniGitHubAction` currently uses the wrong `api.xygeni.io`, because when the "download scanner+unzip" was changed  by "download install script + run", the base URL was not changed. This is because the scanner, in the beginning, was downloaded from the api. Of course the install scripts are in get.xygeni.io. Probably we should get rid of the download scanner endpoint and place all downloadable things in the get.xygeni.io for production, or a "static files area" in the webserver (for labdev).

**Comment by nico-car** [comment]
Tested in LabDev env with the user nicolas.carmona+testing3@xygeni.io and private repository: [nico-car/TestingDuckDrinker](https://github.com/nico-car/TestingDuckDrinker) with the following github action:

```
on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  xygeni-scan:
    runs-on: ubuntu-latest
    name: xygeni-github-action
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Xygeni-Scanner
      uses: xygeni/xygeni-action@v2.0
      id: Xygeni-Scanner
      with:
        token: ${{ secrets.XYGENI_TOKEN }}
        xygeni_url: https://apidev.xygeni.io/deps-doctor-service
```
